apiVersion: iam.confluent.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: confluent-provider
spec:
  forProvider:
    name: crossplane-test
    description: "Emilllllllllll"
  providerConfigRef:
    name: confluent-provider