apiVersion: schemaregistry.confluent.crossplane.io/v1alpha1
kind: Schema
metadata:
  name: my-schema
spec:
  forProvider:
    subject: test-subject
    schema: '{"type" : "record", "namespace" : "Example", "name" : "Employee", "fields" : [{"name" : "Name", "type" : "string"}, {"name" : "Age", "type" : "int"}]}'
    schemaType: AVRO
    environment: env-zvzz7
  providerConfigRef:
    name: confluent-provider