apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: confluent-provider-secret
type: Opaque
data:
  apiCredentials:
    - identifier: schemaregistry.confluent.crossplane.io/v1alpha1
      key: xyz
      secret: zyx
---
apiVersion: confluent.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: confluent-provider
spec: 
  credentials:    
    source: Environment
    env: 
      name: CONFLUENT_PROVIDER_CREDENTIALS
  apiCredentials:
    secretRef:
      namespace: crossplane-system
      name: confluent-provider-secret
      key: apiCredentials
