apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: confluent-provider-secret
type: Opaque
data:
  username: dXNlcm5hbWUK
  password: cGFzc3dvcmQK
---
apiVersion: confluent.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: confluent-provider
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: confluent-provider-secret
      key: credentials
