apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: confluent-provider-secret
type: Opaque
data:
  apiKeys:
    - name: schema-controller
      apiKey: xyz
      apiSecret: zyx
    - name: my-controller
      apiKey: xyz
      apiSecret: zyx
---
apiVersion: confluent.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: confluent-provider
spec: 
  apiKeys:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: confluent-provider-secret
      key: apiKeys
