name: Provider confluent CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_REGISTRY: dfds

jobs:
  ci:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: prereqs for make
        run: make submodules
      - name: lint
        run: make lint
      - name: prereqs for test
        run: go mod vendor
      - name: install confluent cli
        run: curl -sL --http1.1 https://cnfl.io/cli | sh -s -- latest
      # - name: test
      #   run: ./scripts/test.sh
      - name: build
        run: make build
      - name: docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN}}
      - name: docker tag controller
        run: docker tag ${{ env.BUILD_REGISTRY }}/provider-confluent-controller-amd64:latest ${{ secrets.DOCKERHUB_USERNAME }}/provider-confluent-controller:latest
      - name: docker push controller
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/provider-confluent-controller:latest
      - name: docker tag controller
        run: docker tag ${{ env.BUILD_REGISTRY }}/provider-confluent-amd64:latest ${{ secrets.DOCKERHUB_USERNAME }}/provider-confluent:latest
      - name: docker push package
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/provider-confluent:latest